#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SelectRow.Resource", IsApplication=true)]

namespace SelectRow
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int row_background = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int row_pressed_end = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int row_pressed_start = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int row_selected = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int row_text1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int row_text2 = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int FlowerBuds = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Fruits = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Legumes = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list_item_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Tubers = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Vegetables = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Image = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int Text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Text2 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int listView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int row_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
